name: "Pull Request Docs Check"

on: 
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        pip install -r requirements_dev.in
    - name: Generate pre-build data
      run: cd doc/ && make generate_data
    - name: Build docs
      run: cd doc/ && make html
