name: "Pull Request Docs Check"

on: 
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate pre-build data
      run: cd doc/ && make generated
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
