name: "Pull Request Docs Check"

on: 
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.in
    - name: Generate pre-build data
      run: cd doc/ && make generate_data
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
