# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements_dev.in
    - name: Linter
      run: |
        # Stop the build if there are syntax errors or some basic mistakes.
        pylint recipipe tests
    - name: Run tests
      env:
        # Needed for downloading test data in the example notebooks.
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        coverage run --source=recipipe -m pytest
    - name: Test coverage
      run: |
        # Never coverage under 100%!
        coverage report --fail-under=100
    - name: Coveralls upload
      # It was impossible for me to upload parallel versions and
      # merge them at the end. Errors everywhere.
      # For the moment I'm going to upload only the 3.8 coverage.
      if: matrix.python-version == '3.8'  # double quotes do not work here...
      run: |
        coveralls debug
        coveralls
